apiVersion: v1
kind: Template
labels:
  template: backend-icinga2-pvc-template
metadata:
  name: backend-icinga2-pvc
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
        
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}-2 "
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 300Mi
parameters:
- name: APP_NAME
  value: core
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE