apiVersion: v1
kind: Template
labels:
  template: frontend-icinga2-pvc-template
metadata:
  name: frontend-icinga2-pvc
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

parameters:
- name: APP_NAME
  value: frontend
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE