apiVersion: v1
kind: Template
labels:
  template: frontend-icinga2-route-template
metadata:
  name: frontend-icinga2-route
objects: 
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}"
    creationTimestamp:     
  spec:
    host: "${SERVICE_NAME}.${URL_SUFIX}"
    to:
      kind: Service
      name: "${APP_NAME}-${SERVICE_NAME}"

    
parameters:
- name: ROUTE_HOST_PREFIX
  value: devops-icinga2
- description: The name of the OpenShift Service exposed for the  container.
  displayName: Service Name
  name: APP_NAME
  value: frontend
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE
  required: true
- name: URL_SUFIX
  value: 