apiVersion: v1
kind: Template
labels:
  template: frontend-icinga2-dc-template
metadata:
  name: frontend-icinga2-dc
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}-${SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_NAME}-${SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${APP_NAME}-${SERVICE_NAME}
      spec:
        volumes:
          -
            name: ${APP_NAME}-${SERVICE_NAME}
            persistentVolumeClaim:
              claimName: ${APP_NAME}-${SERVICE_NAME}
        containers:
        - capabilities: {}
          image: icinga/web
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}-${SERVICE_NAME}
          securityContext:
            supplementalGroups: [0]
            runAsUser: 0
          env:
            -
              name: "MYSQL_USER"
              value: "${MYSQL_USER}"
            -
              name: "MYSQL_PASSWORD"
              value: "${MYSQL_PASSWORD}"
            -
              name: "MYSQL_DATABASE"
              value: "${MYSQL_DATABASE}"
          ports:
              -
                containerPort: 80
              -
                containerPort: 636
          volumeMounts:
              -
                name:  ${APP_NAME}-${SERVICE_NAME}
                mountPath: "/etc/icingaweb2"
                subPath: icingaweb2

          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
                    
parameters:
- name: SERVICE_NAME
  value: icinga2
- name: APP_NAME
  value: frontend
- name: IMAGE_VERSION
  value: latest
- name: MYSQL_ROOT_PASSWORD
  value: "secret"
- name: MYSQL_USER
  value: "icinga"
- name: MYSQL_PASSWORD
  value: "icinga"
- name: MYSQL_DATABASE
  value: "icinga"
- name: NAMESPACE
  required: true   