apiVersion: v1
kind: Template
labels:
  template: frontend-icinga2-service-template
metadata:
  name: frontend-icinga2-service
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}-${SERVICE_NAME}"
  spec:
    ports:
    - name: ${APP_NAME}-${SERVICE_NAME}
      protocol: TCP
      port: 80
      targetPort: 80
    selector:
      name: "${APP_NAME}-${SERVICE_NAME}"

parameters:
- description: The name of the OpenShift Service exposed for the  container.
  displayName: Service Name
  name: APP_NAME
  value: frontend
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE
  required: true
