apiVersion: v1
kind: Template
labels:
  template: mysql-pvc-template
metadata:
  name: mysql-pvc
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

parameters:
- name: APP_NAME
  value: mysql
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE