apiVersion: v1
kind: Template
labels:
  template: backend-icinga2-is-template
metadata:
  name: backend-icinga2-is
objects: 
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
  spec:
    dockerImageRepository: "${IMAGE}"
    tags:
    - name: ${APP_VERSION}
      from:
        kind: DockerImage
        name: '${IMAGE}'   

parameters:
- name: APP_NAME
  value: mysql
- name: APP_VERSION
  value: latest
- name: SERVICE_NAME
  value: icinga2
- name: IMAGE_VERSION
  value: latest
- name: IMAGE
  required: true
- name: NAMESPACE
  



 