apiVersion: v1
kind: Template
labels:
  template: mysql-service-template
metadata:
  name: mysql-service
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
  spec:
    ports:
    - name: ${APP_NAME}
      protocol: TCP
      port: 3306
      targetPort: 3306
    selector:
      name: ${APP_NAME}

parameters:
- description: The name of the OpenShift Service exposed for the  container.
  displayName: Service Name
  name: APP_NAME
  value: mysql
- name: SERVICE_NAME
  value: icinga2
- name: NAMESPACE
  required: true
